// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQC06PiaPNztoIYdeVZG2GrTl4vmN0Kko',
    appId: '1:808304126525:web:2e07884b4c05631bfb9854',
    messagingSenderId: '808304126525',
    projectId: 'switch-app-8068b',
    authDomain: 'switch-app-8068b.firebaseapp.com',
    storageBucket: 'switch-app-8068b.appspot.com',
    measurementId: 'G-TX8RM0J3QM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZ733vCQscuV9s699hEHyw9hOgQkwgGU',
    appId: '1:808304126525:ios:2a6b0a8c906fab51fb9854',
    messagingSenderId: '808304126525',
    projectId: 'switch-app-8068b',
    storageBucket: 'switch-app-8068b.appspot.com',
    iosClientId: '808304126525-48d6c2vcg0mals59tpggb29g31v1or6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.switchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTZ733vCQscuV9s699hEHyw9hOgQkwgGU',
    appId: '1:808304126525:ios:2a6b0a8c906fab51fb9854',
    messagingSenderId: '808304126525',
    projectId: 'switch-app-8068b',
    storageBucket: 'switch-app-8068b.appspot.com',
    iosClientId: '808304126525-48d6c2vcg0mals59tpggb29g31v1or6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.switchApp',
  );
}
